### ISSUE TITLE
Ability to set custom annotations to Wavefront Proxy

### ISSUE THREAD

**Issue by iAlexBLR** [wavefrontHQ/observability-for-kubernetes#196]
Hi, I'm currently deploying object of Wavefront kind inside of the Kubernetes cluster and wondering if there is possibility of setting up custom annotations to the resources created by the operator in general and for Wavefront Proxy in particular.

Use case: we're using [External Secrets](https://external-secrets.io/v0.8.3/introduction/overview/#externalsecret) to synchronise AWS Secrets Manager secret that contains token for Wavefront Proxy with Kubernetes secrets. Also in order to restart pods of the Wavefront Proxy ones the secret changes we've configured [Reloader](https://github.com/stakater/Reloader). But to make things working we need to set up a specific annotation to the Wavefront Proxy Deployment that will be read by Reloader and it will act accordingly. But as far as I see in the Wavefront object CRD there is no such option.

**Comment by johncornish** [comment]
Hi @iAlexBLR , there hasn't been any activity on this in a while and I hope that means you got the answer you needed from Anil! Closing this as it has become stale.
