### ISSUE TITLE
Configuration for hybrid windows/linux node cluster

### ISSUE THREAD

**Issue by EliMor** [wavefrontHQ/observability-for-kubernetes#452]
The node collector pods are sitting in pending on windows nodes trying to mount a volume:
```sh
MountVolume.SetUp failed for volume "kube-api-access-sptd6" : chown c:\var\lib\kubelet\pods\.......\token: not supported by windows
```

Are windows nodes not supported currently? 
I also didn't see a way to add a node selector in the [full config](https://github.com/wavefrontHQ/observability-for-kubernetes/blob/main/deploy/scenarios/wavefront-full-config.yaml) to just have the node collectors on linux nodes for now if thats the case.

**Comment by johncornish** [comment]
Hi @EliMor , we don't support Windows because of Windows licensing issues.
