### ISSUE TITLE
Multiple applications for 1 proxy

### ISSUE THREAD

**Issue by sergio-moreira-everi** [wavefrontHQ/observability-for-kubernetes#488]
If we have multiple applications within one cluster and want to forward traces to a single proxy, is there a way to differentiate the different applications or do we need 1 proxy per application. 

ie. Is there a way to push the application name variable: https://github.com/wavefrontHQ/observability-for-kubernetes/blob/main/deploy/scenarios/wavefront-full-config.yaml#L161
down to maybe the application layer?

**Comment by oppegard** [comment]
Hi @sergio-moreira-everi, the application name that's configured for distributed tracing in the proxy should be considered a default or fallback application, in case the spans themselves don't include an `application` tag already.

In Wavefront's distributed tracing offering, both `application` and `service` are required tags: https://docs.wavefront.com/trace_data_details.html#application-tags. These tags should be included in all spans emitted by each microservice that comprise a distributed application. E.g. two services might have identifying service tags of `service=payment-processor` and `service=shopping-cart` in their spans, and they also include a common tag of `application=web-shop`.

If your applications are instrumented with OpenTelemetry SDKs, the SDKs should respect these environment variables: https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#general-sdk-configuration. You could set the two required tags by exporting:
- `OTEL_SERVICE_NAME=shopping-cart`
- `OTEL_RESOURCE_ATTRIBUTES=application=web-shop,other-tag=foo`
